# Use the official Python image
FROM python:3.9-slim

# Set working directory inside the container
WORKDIR /app

# Set PYTHONPATH to /app
ENV PYTHONPATH=/app

# Copy the backend files (including app code) into the container
COPY ./app /app

# Copy the tests directory into the container
COPY ./tests /app/tests

# Copy requirements.txt to install dependencies
COPY requirements.txt /app/

# Install dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Run the tests
CMD ["pytest", "--cov=app", "--cov-report=term-missing", "tests/"]
